openapi: 3.0.0
info:
  title: Server Backend
  version: 1.0.0
  description: Server Backend for Node.js
paths:
  /hello:
    get:
      summary: Returns a greeting message
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              example:
                message: Hello, world!
